### ISSUE TITLE
feat(user): change user-logged password

### ISSUE THREAD

**Issue by anggawanridho** [CapstoneProjectKelompok3/NodeJS#41]

**Comment by Fannn03** [comment]
Logged password itu apa? forgot password kah?

**Comment by anggawanridho** [comment]
ganti password user yang sedang login
self password change only

**Comment by Fannn03** [comment]
untuk fiturnya sudah di bicarakan sama anak fe nya? seperti page atau sebagainya?

**Comment by anggawanridho** [comment]
belum mas itu satu dengan api update user yang saya buat kemarin, cuma bagian password pakai api sendiri,
